---
extends: node
rules:
  import/no-commonjs: 0
  import/no-nodejs-modules: 0
  no-console: 1
  semi: 2
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: never
      exports: never
      functions: ignore
